Name:           perl-ExtUtils-Constant
Version:        0.23
Release:        1.efa%{?dist}
Summary:        Generate XS code to import C header constants
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/ExtUtils-Constant/
Source0:        https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/ExtUtils-Constant-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
ExtUtils::Constant facilitates generating C and XS wrapper code to allow
perl modules to AUTOLOAD constants defined in C library header files. It is
principally used by the h2xs utility, on which this code is based. It
doesn't contain the routines to scan header files to extract these
constants.

%prep
%setup -q -n ExtUtils-Constant-%{version}

%build
CFLAGS="%{optflags}" %{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{buildroot}%{_prefix}"
%{__make} %{?_smp_mflags} OPTIMIZE="%{optflags}"

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install

find %{buildroot} -name .packlist -exec %{__rm} {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

# Remove man files (conflicts with perl rpm)
%{__rm} -rf %{buildroot}/%{_mandir}/man3

%{_fixperms} %{buildroot}/*

%check
%{__make} test

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*

%changelog
* Sun Feb 14 2016 Shawn Iverson <shawniverson@gmail.com> - 0.23-1
- Rebuilt for EFA https://efa-project.org

* Tue Sep 02 2014 Dave Cross <dave@mag-sol.com> 0.23-1
- Specfile autogenerated by cpanspec 1.78.
