Name:           perl-Digest-MD5
Version:        2.54
Release:        1.efa%{?dist}
Summary:        Perl interface to the MD5 algorithm
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Digest-MD5/
Source0:        https://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-MD5-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root
BuildRequires:  perl(Digest::base) >= 1.16
BuildRequires:  perl(Test::More)
BuildRequires:  perl(MIME::Base64)
Requires:       perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
Requires:       perl(Digest::base) >= 1.16

%description
The Digest::MD5 module allows you to use the RSA Data Security Inc. MD5
Message Digest algorithm from within Perl programs. The algorithm takes as
input a message of arbitrary length and produces as output a 128-bit
"fingerprint" or "message digest" of the input.

%prep
%setup -q -n Digest-MD5-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{buildroot}%{_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install

find %{buildroot} -name .packlist -exec %{__rm} {} \;
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;

# man files conflict with perl package
%{__rm} -rf %{buildroot}/%{_mandir}/man3

%{_fixperms} %{buildroot}/*

%check
%{__make} test

%files
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Digest*
#%{_mandir}/man3/*

%changelog
* Thu Feb 19 2016 Shawn Iverson <shawniverson@gmail.com> - 2.54-1
- Updated for EFA https://efa-project.org

* Tue Mar 19 2013 Petr Pisar <ppisar@redhat.com> 2.52-1
- Specfile autogenerated by cpanspec 1.78.
