Name:           perl-Test-Pod
Version:        1.51
Release:        1.efa%{?dist}
Summary:        Check for POD errors in files
License:        perl_5
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Pod/
Source0:        https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Pod-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Pod::Simple) >= 3.13
BuildRequires:  perl(Test::Builder::Tester) >= 1.02
BuildRequires:  perl(Test::More) >= 0.62
Requires:       perl(Pod::Simple) >= 3.13
Requires:       perl(Test::Builder::Tester) >= 1.02
Requires:       perl(Test::More) >= 0.62
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Check POD files for errors or warnings in a test file, using Pod::Simple to
do the heavy lifting.

%prep
%setup -q -n Test-Pod-%{version}

%build
CFLAGS="%{optflags}" %{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{buildroot}%{_prefix}"
%{__make} %{?_smp_mflags} OPTIMIZE="%{optflags}"

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install

find %{buildroot} -name .packlist -exec %{__rm} {} \;

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Feb 14 2016 Shawn Iverson <shawniverson@gmail.com> - 1.51-1
- Updated for EFA https://efa-project.org

* Fri Jan 11 2013 David E. Wheeler <david.wheeler@iovation.com> 1.45-1
- Specfile autogenerated by cpanspec 1.78.
