#!/bin/bash
# +--------------------------------------------------------------------+
# EFA update script
# Version 20150410
# +--------------------------------------------------------------------+
# Copyright (C) 2012~2015  http://www.efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# +--------------------------------------------------------------------+

#----------------------------------------------------------------#
# Variables
#----------------------------------------------------------------#
logdir="/var/log/EFA"
gitdlurl="https://raw.githubusercontent.com/E-F-A/v3"
mirror="http://dl.efa-project.org"
mirrorpath="update"
yumexclude="kernel* mysql* postfix* mailscanner* clamav* clamd*"
ADMINEMAIL="`cat /etc/EFA-Config | grep ADMINEMAIL | sed 's/.*://'`"
MAILFROM="$ADMINEMAIL"
MAILTO="$ADMINEMAIL"
MAILSUBJECT="EFA Update Complete For: `hostname`"
SENDMAIL="/usr/lib/sendmail"
TMPMAIL="/tmp/tempmail"
MAILWATCHVERSION="7f6858df83"
IMAGECEBERUSVERSION="1.1"
SPAMASSASSINVERSION="3.4.0"
PYZORVERSION="0.7.0"
VMTOOLSVERSION="9.4.0-1280544"
WEBMINVERSION="1.690-1"
STAGING="/tmp/EFA-Staging"
#----------------------------------------------------------------#


# test setup:
# EFA update scripts fetches .tar.gz file from dl.efa-project.org
# tar.gz file contains all files needed to update (previous from git and dl.efa-project.org)
# tar.gz file structure and naming:
# EFA-Update-<previous version>-<new version>.tar.gz:
#   EFA-Update-3.0.0.7-3.0.0.8.tar.gz
#      /EFA-Version-Upgrade   				<- script that should be launched from this file.
#		/Files/										<- Directory containing binary files
#      /Scripts/									<- Directory containing update scripts (previous git scripts)
#
# Update methode:
# this script downloads the latest EFA-Update.XXXX-XXXX.tar.gz file
# this script runs MD5 checksum for the tar.gz. file
# this script unpacks the tar.gz file to /tmp/EFA-Staging
# this script runs the EFA-Version-Upgrade script