#!/bin/bash
# +--------------------------------------------------------------------+
# EFA update script
# Version 20150410
# +--------------------------------------------------------------------+
# Copyright (C) 2012~2015 http://www.efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# +--------------------------------------------------------------------+

#----------------------------------------------------------------#
# Variables
#----------------------------------------------------------------#
logdir="/var/log/EFA"
gitdlurl="https://raw.githubusercontent.com/E-F-A/v3"
mirror="http://dl.efa-project.org"
mirrorpath="update"
yumexclude="kernel* mysql* postfix* mailscanner* clamav* clamd*"
ADMINEMAIL="`cat /etc/EFA-Config | grep ADMINEMAIL | sed 's/.*://'`"
MAILFROM="$ADMINEMAIL"
MAILTO="$ADMINEMAIL"
MAILSUBJECT="EFA Update Complete For: `hostname`"
SENDMAIL="/usr/lib/sendmail"
TMPMAIL="/tmp/tempmail"

#----------------------------------------------------------------#
# List of current version numbers for the software we use
#----------------------------------------------------------------#
MAILWATCHVERSION="7f6858df83"
IMAGECEBERUSVERSION="1.1"
SPAMASSASSINVERSION="3.4.0"
PYZORVERSION="0.7.0"
VMTOOLSVERSION="9.4.0-1280544"
WEBMINVERSION="1.690-1"
STAGING="/tmp/EFA-Staging"
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# test setup:
# EFA update scripts fetches .tar.gz file from dl.efa-project.org
# tar.gz file contains all files needed to update (previous from git and dl.efa-project.org)
# tar.gz file structure and naming:
# EFA-Update-<previous version>-<new version>.tar.gz:
#   EFA-Update-3.0.0.7-3.0.0.8.tar.gz
#      /EFA-Version-Upgrade   				<- script that should be launched from this file.
#		/Files/										<- Directory containing binary files
#      /Scripts/									<- Directory containing update scripts (previous git scripts)
#
# Update methode:
# this script downloads the latest EFA-Update.XXXX-XXXX.tar.gz file
# this script runs MD5 checksum for the tar.gz. file
# this script unpacks the tar.gz file to /tmp/EFA-Staging
# this script runs the EFA-Version-Upgrade script
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# get-update path
#----------------------------------------------------------------#
function get_update_path() {
  get_cversion
  if [[ $CVERSION == "EFA-3.0.0.0" ]]
    then
      # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.1" ]]
    then
      # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.2" ]]
    then
    # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.3" ]]
    then
    # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.4" ]]
    then
    # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.5" ]]
    then
    # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.6" ]]
    then
    # do stuff
  elif [[ $CVERSION == "EFA-3.0.0.7" ]]
    then
    # do stuff
  fi
}
#----------------------------------------------------------------#


#----------------------------------------------------------------#
# Function get current version number
#----------------------------------------------------------------#
function get_cversion() {
  if [ -f /etc/EFA-Version ]
    then
      CVERSION="`head -1 /etc/EFA-Version`"
    else
      echo "ERROR: No valid version file found on this system."
      echo "ERROR: exiting now"
      exit 0
  fi

  # Check if we run an beta version
  if [[ $CVERSION =~ ^EFA\-[0-9]{1}\.[0-9]{1}\.[0-9]{1}\.[0-9]{1}-beta$ ]]
    then
      echo "ERROR: You seem to be running an beta version, no upgrade possible."
      echo "ERROR: please look at http://www.efa-project.org for more information."
      echo "ERROR: exiting now"
      exit 0
  fi

  # Check if CVERSION is an valid Version file
  if ! [[ $CVERSION =~ ^EFA\-[0-9]{1}\.[0-9]{1}\.[0-9]{1}\.[0-9]{1}$ ]]
    then
      echo "ERROR: The version file on your system does not seem to be valid."
      echo "ERROR: exiting now"
      exit 0
  fi
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Check if we are root
#----------------------------------------------------------------#
function user_check() {
  if [ `whoami` == root ]
    then
      echo "[EFA] Good you are root"
  else
    echo "[EFA] Please become root to run this update"
    exit 0
  fi
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Where to start
#----------------------------------------------------------------#
user_check
get_update_path
