#!/bin/bash
# +--------------------------------------------------------------------+
# EFA update script
# Version 20140201
# +--------------------------------------------------------------------+
# Copyright (C) 2012~2014  http://www.efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# +--------------------------------------------------------------------+

#----------------------------------------------------------------#
# Variables
#----------------------------------------------------------------#
logdir="/var/log/EFA"
gitdlurl="https://raw.github.com/E-F-A/v3/master/"
mirror="http://dl.efa-project.org"
mirrorpath="/update"
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# get-update path
#----------------------------------------------------------------#
function get_update_path() {
  get_cversion
  if [[ $CVERSION == "EFA-3.0.0.0" ]]
    then
      update-3.0.0.1
      update-3.0.0.2
      update-3.0.0.3
  elif [[ $CVERSION == "EFA-3.0.0.1" ]]
    then
      update-3.0.0.2
      update-3.0.0.3
  elif [[ $CVERSION == "EFA-3.0.0.2" ]]
    then
      update-3.0.0.3
  fi
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Update to EFA-3.0.0.3
#----------------------------------------------------------------#
function update-3.0.0.3() {

  echo "Staring update to E.F.A. 3.0.0.3"
  VERSION="3.0.0.3"
 
  # Upgrade OS to latest version
  yum -y update

  # grab latest version of EFA-Configure
  rm -f /usr/local/sbin/EFA-Configure
  /usr/bin/wget -O /usr/local/sbin/EFA-Configure $gitdlurl/build/EFA/EFA-Configure
  chmod 700 /usr/local/sbin/EFA-Configure

  # Issue #16 System/db/settings backup
  mkdir -p /var/EFA/backup
  /usr/bin/wget -O /usr/local/sbin/EFA-Backup $gitdlurl/build/EFA/EFA-Backup
  chmod 700 /usr/local/sbin/EFA-Backup
  /usr/bin/wget -O /etc/cron.daily/EFA-Backup-cron $gitdlurl/build/EFA/EFA-Backup-cron
  chmod 700 /etc/cron.daily/EFA-Backup-cron

  # Issue #17 Trusted Network Rules
  touch /etc/sysconfig/EFA_trusted_networks
  yum -y install perl-Net-Netmask
  /usr/bin/wget -O /var/www/html/denylearned.html $gitdlurl/build/EFA/denylearned.html
  rm -f /var/www/cgi-bin/learn-msg.cgi
  /usr/bin/wget -O /var/www/cgi-bin/learn-msg.cgi $gitdlurl/build/EFA/learn-msg.cgi
  chmod 755 /var/www/cgi-bin/learn-msg.cgi
  EFASQLPWD=`grep EFASQLPWD /etc/EFA-Config | sed 's/^.*://'`
  sed -i "/^\$db_pass =/ c\$db_pass = \"$EFASQLPWD\";" /var/www/cgi-bin/learn-msg.cgi
  
  #  Issue #50, clean sqlgrey source files
  rm -rf /etc/cron.weekly/sqlgrey-1.8.0*

  #  Issue #53, fix postfix queues after yum update
  #  Todo:  add this to every future update as a standard change
  chown postfix:apache /var/spool/postfix/incoming
  chown postfix:apache /var/spool/postfix/hold
  chmod 740 /var/spool/postfix/incoming
  chmod 740 /var/spool/postfix/hold
  
  # Version update
  echo "EFA-$VERSION" > /etc/EFA-Version
  sed -i "/--- Welcome to EFA-/ c\--- Welcome to EFA-$VERSION ---" /etc/issue 
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Update to EFA-3.0.0.2 
#----------------------------------------------------------------#
function update-3.0.0.2() {

  echo "Staring update to E.F.A. 3.0.0.2"
  VERSION="3.0.0.2"
 
  # Upgrade OS to latest version
  yum -y update
  
   # fix issue Urgent: learn-msg.cgi broken #44
  EFASQLPWD=`grep EFASQLPWD /etc/EFA-Config | sed 's/^.*://'`
  sed -i "/^\$db_pass =/ c\$db_pass = \"$EFASQLPWD\";" /var/www/cgi-bin/learn-msg.cgi
  
  echo "EFA-$VERSION" > /etc/EFA-Version
  sed -i "/--- Welcome to EFA-/ c\--- Welcome to EFA-$VERSION ---" /etc/issue 
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Update to EFA-3.0.0.1 
#----------------------------------------------------------------#
function update-3.0.0.1() {
  echo "Staring update to E.F.A. 3.0.0.1"
  VERSION="3.0.0.1"
  
  # Upgrade OS to latest version
  yum -y update
  
  # grab latest version of EFA-Configure
  rm -f /usr/local/sbin/EFA-Configure
  /usr/bin/wget -O /usr/local/sbin/EFA-Configure $gitdlurl/build/EFA/EFA-Configure
  chmod 700 /usr/local/sbin/EFA-Configure
  
  # fix issue 32 clean quarantine not enabled
  sed -i '/$disabled = 1;/ c\$disabled = 0;' /etc/cron.daily/clean.quarantine

  # fix issue 23 
  yum -y remove cyrus-sasl-sql cyrus-sasl-ldap

  # fix issue 24 Disable Deliver Cleaned Messages
  sed -i '/^Deliver Cleaned Messages =/ c\Deliver Cleaned Messages = No' /etc/MailScanner/MailScanner.conf
  
  # Download latest learn-msg.cgi (fix issue 41)
  rm -f /var/www/cgi-bin/learn-msg.cgi
  cd /var/www/cgi-bin
  wget $gitdlurl/build/EFA/learn-msg.cgi
  chmod 755 learn-msg.cgi

  # Update Version Number
  echo "EFA-$VERSION" > /etc/EFA-Version
  sed -i "/--- Welcome to EFA-/ c\--- Welcome to EFA-$VERSION ---" /etc/issue  
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Function get current version number
#----------------------------------------------------------------#
function get_cversion() {
  if [ -f /etc/EFA-Version ]
    then
      CVERSION="`head -1 /etc/EFA-Version`" 
    else
      echo "ERROR: No valid version file found on this system." 
      echo "ERROR: exiting now"
      exit 0
  fi
  
  # Check if we run an beta version
  if [[ $CVERSION =~ ^EFA\-[0-9]{1}\.[0-9]{1}\.[0-9]{1}\.[0-9]{1}-beta$ ]]
    then
      echo "ERROR: You seem to be running an beta version, no upgrade possible."
      echo "ERROR: please look at http://www.efa-project.org for more information."
      echo "ERROR: exiting now"
      exit 0
  fi
  
  # Check if CVERSION is an valid Version file
  if ! [[ $CVERSION =~ ^EFA\-[0-9]{1}\.[0-9]{1}\.[0-9]{1}\.[0-9]{1}$ ]]
    then
      echo "ERROR: The version file on your system does not seem to be valid."
      echo "ERROR: exiting now"
      exit 0
  fi
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Check if we are root
#----------------------------------------------------------------#
function user_check() {
  if [ `whoami` == root ]
    then
      echo "[EFA] Good you are root"
  else
    echo "[EFA] Please become root to run this update"
    exit 0
  fi
}
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Where to start
#----------------------------------------------------------------#
user_check
get_update_path
