Name:           perl-Text-Balanced
Version:        2.03
Release:        1.efa%{?dist}
Summary:        Extract delimited text sequences from strings
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Text-Balanced/
Source0:        http://www.cpan.org/authors/id/A/AD/ADAMK/Text-Balanced-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.47
Requires:       perl(Test::More) >= 0.47
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The various extract_... subroutines may be used to extract a delimited
substring, possibly after skipping a specified prefix string. By default,
that prefix is optional whitespace (/\s*/), but you can change it to
whatever you wish (see below).

%prep
%setup -q -n Text-Balanced-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

# Remove man conflict with perl package
rm -rf $RPM_BUILD_ROOT/%{_mandir}/man3

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README
%{perl_vendorlib}/*

%changelog
* Sun Feb 28 2016 Shawn Iverson <shawniverson@gmail.com> - 2.03-1
- Updated for EFA https://efa-project.org

* Tue May 18 2010 Dave Cross <dave@mag-sol.com> 2.02-1
- Specfile autogenerated by cpanspec 1.78.
